### ISSUE TITLE
Add node_modules to .gitignore

### ISSUE THREAD

**Issue by pt1602** [Will513r/FullstackBMICalc#1]
Hey Will,

it is not recommended to add the node_modules directory to repository. It contains dependencies which only should be installed on your local machine or the server.  

To prevent this you should add a `.gitignore` file to your repository, which escapes the directory like this:

```text
node_modules
```

**Comment by Will513r** [comment]
do i create it as a folder and just add node_modules?  what about the packages?

**Comment by Will513r** [comment]
I think i did it correctly

**Comment by pt1602** [comment]
You need to create the file with a dot before, like this: `.gitignore` Then delete the `node_modules` and run `npm install` again and commit your changes.

The needed dependencies can be copied out of the `node_modules` directory by a service `gulp`, `grunt` or `webpack`. There are also other ways to handle this, but thats the way I do it.

**Comment by Will513r** [comment]
I think i did it by adding node_modules/ to git ignore then running git rm -r --cached node_modules    But my understanding is to always create git ignore for node moving forward  I appreciate you help!!!
